#+TITLE: Emacs Configuration for Productivity, Planning, "Getting Things Done" and Knowledge Management with Org Mode

* Package Management
** Set up package management and ensure that all required packages are installed
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
  ;; Code above enables lexical scoping so lambdas can capture variables (needed for async code)

  (require 'package)

  ;; Initialize package sources if needed
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  ;; Refresh package contents if needed
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Install use-package if missing
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** Load Local Configuration
#+begin_src emacs-lisp
  (let ((local-file (expand-file-name "local.el" user-emacs-directory)))
    (if (file-exists-p local-file)
        (load local-file)
      (user-error "Missing required local config file: %s" local-file)))
#+end_src

** Load Local Modules
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
  (require 'ps-utils)
  (require 'ps-links)
  (require 'ps-done)
  (require 'ps-git-sync)
  (require 'ps-agenda-emoji)
  (require 'ps-agenda-icons)
  (require 'ps-schedule-icons)
  (require 'ps-blank-lines)
  (require 'ps-availability)
  (require 'ps-conflicts)
  (require 'ps-timezone)
#+end_src

** Availability Settings
#+begin_src emacs-lisp
  (setq ps/org-avail-days             15
        ps/org-avail-work-start       "10:00"
        ps/org-avail-work-end         "22:00"
        ps/org-avail-buffer-minutes   15
        ps/org-avail-min-duration     30
        ps/org-avail-include-weekends nil
        ps/org-avail-time-format      "12h"
        ps/org-avail-layout           "bullets")
#+end_src

** Conflict Settings
#+begin_src emacs-lisp
  (setq ps/conflicts-gap-minutes    15
        ps/conflicts-include-past   nil)
#+end_src

** Done Task Settings
#+begin_src emacs-lisp
  (setq ps/done-fade-color "gray75")
#+end_src

** Git Sync Settings
#+begin_src emacs-lisp
  (setq ps/git-sync-interval 60)
#+end_src

** Schedule Icon Settings
#+begin_src emacs-lisp
  (setq ps/schedule-icons-scheduled "⏱ "
        ps/schedule-icons-deadline  "⚑ "
        ps/schedule-icons-face      '(:foreground "#000000" :weight bold))
#+end_src

* User Interface
** Basic UI Tweaks
#+begin_src emacs-lisp
  ;; Disable the splash screen
  (setq inhibit-splash-screen t)

  ;; Disable tooltips
  (tooltip-mode -1)

  ;; Disable the toolbar
  (tool-bar-mode -1)
#+end_src

** Line Numbers
#+begin_src emacs-lisp
  ;; Show column number in mode line
  (column-number-mode)

  ;; Display line numbers globally
  (global-display-line-numbers-mode t)

  ;; Disable line numbers for specific modes
  (dolist (mode '(term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

  ;; Disable line numbers for neotree
  (with-eval-after-load 'neotree
    (add-hook 'neo-after-create-hook
              (lambda (&rest _)
                (display-line-numbers-mode 0))))
#+end_src

** Always use spaces for indentation
#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
#+end_src

** Word wrap (but only in text mode, not in agenda)
#+begin_src emacs-lisp
  ;; https://www.inmotionhosting.com/support/edu/software/how-to-wrap-text-in-emacs/
  (add-hook 'text-mode-hook 'visual-line-mode)
#+end_src

** Font
#+begin_src emacs-lisp
  ;; Define the font variable globally
  (defvar main-font "default-font"
    "The main font used for Org mode and other settings.")

  ;; Set the default font based on system type
  (setq main-font (cond
                   ((eq system-type 'darwin) "Monaco-14")
                   ((eq system-type 'windows-nt) "Consolas-11")
                   ((eq system-type 'gnu/linux) "monospace-10")
                   (t "default-font")))

  ;; Apply the default font
  (set-face-attribute 'default nil :font main-font)
#+end_src

** Solarized Light Theme
#+begin_src emacs-lisp
  (use-package solarized-theme
    :config
    (setq
     ;; Make the fringe stand out from the background
     solarized-distinct-fringe-background nil

     ;; Don't change the font for some headings and titles
     solarized-use-variable-pitch nil

     ;; Make the modeline high contrast
     solarized-high-contrast-mode-line nil

     ;; Use less bolding
     solarized-use-less-bold t

     ;; Use more italics
     solarized-use-more-italic t

     ;; Use less colors for indicators such as git:gutter, flycheck and similar
     solarized-emphasize-indicators nil

     ;; Don't change size of org-mode headlines (but keep other size-changes)
     solarized-scale-org-headlines nil

     ;; Avoid all font-size changes
     solarized-height-minus-1 1.0
     solarized-height-plus-1 1.0
     solarized-height-plus-2 1.0
     solarized-height-plus-3 1.0
     solarized-height-plus-4 1.0)

    (load-theme 'solarized-light t))
#+end_src

* Org Mode
** Org Agenda
#+begin_src emacs-lisp
  ;; Define custom TODO keywords/states
  (setq org-todo-keywords
        '((sequence
           "TODO(t)"
           "NEXT(n)"
           "IN-PROGRESS(i)"
           "WAITING(w)"
           "SOMEDAY(s)"
           "|"
           "DONE(d)")))

  ;; Automatically add all Org files in the specified directory to the agenda
  ;; https://stackoverflow.com/questions/11384516/how-to-make-all-org-files-under-a-folder-added-in-agenda-list-automatically
  (setq org-agenda-files
        (directory-files-recursively
         (concat my-org-base-directory "Plans/")
         "\\.org$"))

  ;; Fix displaying "???" in agenda view columns
  ;; https://www.reddit.com/r/emacs/comments/s9hl74/mystery_question_marks_on_my_agenda/
  ;; https://emacs.stackexchange.com/questions/42006/trouble-with-org-mode-cache-find-error
  (setq org-element-use-cache nil)

  ;; Allow Emacs Lisp code blocks to be executed without confirmation
  (setq org-confirm-babel-evaluate
        (lambda (lang body)
          (not (string= lang "emacs-lisp"))))

  ;; Set a global keybinding for accessing Org agenda
  (define-key global-map "\C-ca" 'org-agenda)
#+end_src

** Add icons in agenda view
Icon-loading logic lives in =lisp/ps-agenda-icons.el=. The =prefix-format= below is a
layout preference and stays here. Leaving the icon directory empty/absent disables icons.
#+begin_src emacs-lisp
  (ps/agenda-icons-apply (concat my-org-base-directory "Icons/"))

  ;; Reserve space for the category name (max 14 chars in my case) next to the icon.
  (setq org-agenda-prefix-format
        '((agenda . " %-3i %-15:c%?-12t% s")
          (todo . " %-3i %-15:c")
          (tags . " %-3i %-15:c")
          (search . " %-3i %-15:c")))
#+end_src

** Improve appeareance using org-modern
#+begin_src emacs-lisp
  (use-package org-modern
    :ensure t
    :hook ((org-mode . org-modern-mode)
           (org-agenda-finalize . org-modern-agenda))
    :config
    ;; Set larger font for timestamp
    (set-face-attribute 'org-modern-date-active nil
                        :height 1.2
                        :foreground "gray30"
                        :background "gray90")

    (set-face-attribute 'org-modern-time-active nil
                        :height 1.2
                        :foreground "gray30"
                        :background "gray80")

    (set-face-attribute 'org-modern-date-inactive nil
                        :height 1.2
                        :foreground "gray75"
                        :background "gray90")

    (set-face-attribute 'org-modern-time-inactive nil
                        :height 1.2
                        :foreground "gray75"
                        :background "gray80")

    ;; Disable modern bullets
    (setq org-modern-star nil)

    ;; Monochrome TODO keywords
    (custom-set-faces
     '(org-todo ((t (:foreground "gainsboro" :background "gray20"))))
     '(org-headline-done ((t (:foreground "gray75" :strike-through t))))))
#+end_src

** Replace SCHEDULED / DEADLINE labels with icons
Logic lives in =lisp/ps-schedule-icons.el=. Icons and face are set in the Schedule Icon
Settings block above.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook #'ps/schedule-icons-enable)
#+end_src

** Fade and fold DONE tasks
Logic lives in =lisp/ps-done.el=. The fade color is set in the Done Task Settings block above.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook #'ps/done-setup-hooks)
#+end_src

** Gray out Org Metadata
#+begin_src emacs-lisp
  ;; Apply gray color directly to Org's native metadata faces
  (defun my/org-apply-metadata-fade ()
    "Apply gray color to all #+ metadata lines natively."
    ;; Changes faces like `#+TIMEZONE:` and `#+PROPERTY:`
    (set-face-attribute 'org-meta-line nil :foreground "gray85")
    ;; Changes the `#+TITLE:` label specifically
    (set-face-attribute 'org-document-info-keyword nil :foreground "gray85")
    ;; Changes the actual value (e.g., "Interviews") next to TITLE
    (set-face-attribute 'org-document-info nil :foreground "gray85"))

  ;; Run it on mode start
  (add-hook 'org-mode-hook #'my/org-apply-metadata-fade)
#+end_src

** Keep blank lines visible when cycling
The DONE collapse/expand commands themselves live in =lisp/ps-done.el=.
#+begin_src emacs-lisp
  ;; Keep blank lines visible when manually cycling with TAB (org-cycle)
  ;; https://gist.github.com/jeffkreeftmeijer/597b40f6cb087c937b5a591db7846012
  (setq org-cycle-separator-lines -1)
#+end_src

** Make sure tags are visible in the agenda view
#+begin_src emacs-lisp
  (setq org-agenda-tags-column -120)
#+end_src

** Auto-save Org buffers
#+begin_src emacs-lisp
  ;; Auto-save all Org buffers
  ;; https://christiantietze.de/posts/2019/03/sync-emacs-org-files/
  (add-hook 'auto-save-hook 'org-save-all-org-buffers)

  ;; Automatically revert buffers when files change on disk
  (global-auto-revert-mode t)
#+end_src

** Enhanced bullets using =org-superstar=
#+begin_src emacs-lisp
  (use-package org-superstar
    :hook (org-mode . org-superstar-mode)
    :config
    ;; Disable leading dots for bullets
    ;; https://www.reddit.com/r/orgmode/comments/pfgcql/comment/hb4g8j0/
    (setq org-superstar-leading-bullet ?\s))

  ;; Slightly increase header fonts depending on the level
  ;; https://stackoverflow.com/questions/77332358/how-can-i-adjust-the-fonts-and-sizes-of-bullets-in-org-superstar
  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.04))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.03))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.02))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.01))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.0)))))
#+end_src

** Org Super Agenda
#+begin_src emacs-lisp
  (use-package org-super-agenda
    :after org-agenda
    :init
    (setq org-agenda-skip-scheduled-if-done t
          org-agenda-skip-deadline-if-done t
          org-agenda-include-deadlines t
          org-agenda-block-separator nil
          org-agenda-compact-blocks nil
          org-agenda-start-day nil ;; i.e. today
          org-agenda-span 1
          org-agenda-start-on-weekday nil)

    (setq org-agenda-custom-commands
          '(("c" "Super Agenda"
             ((agenda "" ((org-agenda-overriding-header "")
                          (org-super-agenda-groups
                           '((:name "Due today:"
                                    :deadline today
                                    :order 2)
                             (:name "Overdue:"
                                    :deadline past
                                    :order 3)
                             (:name "Scheduled earlier:"
                                    :scheduled past
                                    :order 4)
                             (:name "Due soon:"
                                    :deadline future
                                    :order 5)
                             (:name "Schedule:"
                                    :time-grid t
                                    :date today
                                    :order 1)))))
              (tags-todo "+PRIORITY=\"A\""
                         ((org-agenda-overriding-header "\n High-priority:")))
              (todo "IN-PROGRESS"
                    ((org-agenda-overriding-header "\n In progress:")))))
            ("n" "NEXT tasks"
             ((todo "NEXT")))))

    :config
    (org-super-agenda-mode))
#+end_src

** Visually enhance Org Agenda tasks with emojis for faster recognition
Logic lives in =lisp/ps-agenda-emoji.el= (it shells out to
=scripts/org_emoji_matcher.py=). The conflict-check agenda hook from
=ps-conflicts= is also registered here.
#+begin_src emacs-lisp
  (ps/agenda-emoji-setup)
  (add-hook 'org-agenda-finalize-hook #'ps/conflicts--agenda-schedule-check)
#+end_src

** =org-journal=
#+begin_src emacs-lisp
  (use-package org-journal
  :config
  ;; TODO Comment these settings
  (setq org-journal-file-format "%Y-%m-%d.org"
        org-extend-today-until 4
        org-journal-file-type 'weekly
        org-journal-date-format "%A, %d %B %Y"
        org-journal-dir (concat my-org-base-directory "Journal/")))
#+end_src

** Start week on Monday in calendars
#+begin_src emacs-lisp
  ;; https://emacs.stackexchange.com/questions/42571/org-agenda-date-prompt-mini-calendar-start-week-on-monday
  (setq calendar-week-start-day 1)
#+end_src

** Do not add CLOSED timestamp when completing a task
#+begin_src emacs-lisp
  (setq org-log-done nil)
#+end_src

** Prevent org-mode from collapsing yanked (pasted) subtrees
#+begin_src emacs-lisp
  (setq org-yank-folded-subtrees nil)
#+end_src

** Disable clock report so that it does not show in agenda
#+begin_src emacs-lisp
  (setq org-agenda-start-with-clockreport-mode nil)
#+end_src

* Workflow Enhancements
** =ivy=, =counsel=, and =swiper= for enhanced completion and searching
#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    ;; TODO Document these settings
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x b" . counsel-ibuffer)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . counsel-minibuffer-history)))

  (use-package ivy-rich
    :init (ivy-rich-mode 1))
#+end_src

** =projectile= and =counsel-projectile= to search in all files
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (projectile-mode +1)
    ;; Remove the Projectile menu from the menu bar
    (define-key projectile-mode-map [menu-bar projectile] nil))

  (use-package counsel-projectile
    :ensure t
    :config
    (counsel-projectile-mode))

  (global-set-key (kbd "s-r") 'counsel-projectile-rg)
#+end_src

** =helpful= for enhanced help buffers
#+begin_src emacs-lisp
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+end_src

** =which-key= for displaying available keybindings
#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config (setq which-key-idle-delay 0.3))
#+end_src

** Define custom org link for Obsidian to make them short
Logic lives in =lisp/ps-links.el=. Links may be written in full or short form:
=[[obsidian://open?vault=obsidian&file=Maps]]= or =[[obsidian:Maps]]=.
#+begin_src emacs-lisp
  ;; Register the obsidian: link type and per-buffer font-lock composition.
  (org-add-link-type "obsidian" #'ps/obsidian--open-note)
  (add-hook 'org-mode-hook #'ps/org-enable-obsidian-links)

  (global-set-key (kbd "<f4>") #'ps/insert-obsidian-link-from-clipboard)
  (global-set-key (kbd "<f5>") #'ps/insert-obsidian-link-prompt)
#+end_src

** Auto-insert org-links with fetched page title
Logic lives in =lisp/ps-links.el= (uses the string helpers in =ps-utils=).
#+begin_src emacs-lisp
  (global-set-key (kbd "<f6>") #'ps/org-insert-link-async)
#+end_src

* File and Directory Management
** Default directory
#+begin_src emacs-lisp
  (setq default-directory (concat my-org-base-directory "Plans/"))
#+end_src

** Workaround error on startup regarding unsupported =ls --dired= on MacOS
#+begin_src emacs-lisp
  ;; https://stackoverflow.com/questions/25125200/emacs-error-ls-does-not-support-dired
  (when (string= system-type "darwin")
    (setq dired-use-ls-dired nil))
#+end_src

** =neotree= for file explorer functionality
#+begin_src emacs-lisp
  (setq neo-autorefresh nil)

  (use-package neotree
    :config
    (neotree-dir my-org-base-directory))

  (defun my-neotree-customizations (&optional _)
    (setq left-margin-width 1) ;; add extra 1 space for left margin
    (set-window-buffer nil (current-buffer))) ;; refresh buffer display

  (add-hook 'neo-after-create-hook 'my-neotree-customizations)

  ;; Ensure refresh after startup (if neotree is opened early)
  (add-hook 'emacs-startup-hook
    (lambda ()
      (run-at-time "0.1 sec" nil #'my-neotree-customizations)))

  (with-eval-after-load 'neotree
    ;; Avoid redisplay races during auto-revert
    (advice-add
     'neo-buffer--get-filename-current-line
     :around
     (lambda (orig-fun &rest args)
       (ignore-errors
         (apply orig-fun args)))))
#+end_src

* Menu Bar and Keybindings
** F7 to Reinsert Empty Lines
Logic lives in =lisp/ps-blank-lines.el=.
#+begin_src emacs-lisp
  (global-set-key [f7] #'ps/blank-lines-reinsert)
#+end_src

** F8 to Show Neotree
#+begin_src emacs-lisp
  (global-set-key [f8] 'neotree-toggle)
#+end_src

** F9 to Show Agenda
#+begin_src emacs-lisp
  ;; Show the agenda with the "NEXT" tasks and delete other windows
  (defun my-show-agenda ()
    (interactive)
    (org-todo-list "NEXT")
    (delete-other-windows))

  (global-set-key [f9] 'my-show-agenda)
#+end_src

** F10 to Open Config File
#+begin_src emacs-lisp
  (defun my-open-config-file ()
    (interactive)
    (find-file (expand-file-name "config.org" user-emacs-directory)))

  (global-set-key [f10] 'my-open-config-file)
#+end_src

** GTD Menu
#+begin_src emacs-lisp
  ;; Add a custom "GTD" menu to the menu bar
  ;; https://emacs.stackexchange.com/questions/15093/how-to-add-an-item-to-the-menu-bar
  (defvar my-menu-bar-menu (make-sparse-keymap "GTD"))
  (define-key global-map [menu-bar my-menu] (cons "GTD" my-menu-bar-menu))

  ;; Insert GTD before the Help menu
  (setq menu-bar-final-items (append menu-bar-final-items '(my-menu)))

  ;; Define the menu items for GTD
  (define-key my-menu-bar-menu [my-cmd8]
              '(menu-item "Open Config File" my-open-config-file :help "Open the Emacs config file"))
  (define-key my-menu-bar-menu [my-cmd7]
              '(menu-item "Toggle Neotree" neotree-toggle :help "Toggle Neotree"))
  (define-key my-menu-bar-menu [my-cmd6]
              '(menu-item "Show Agenda" my-show-agenda :help "Show Agenda"))
  (define-key my-menu-bar-menu [my-cmd5]
              '(menu-item "Reinsert Empty Lines" ps/blank-lines-reinsert :help "Reinsert Empty Lines"))
  (define-key my-menu-bar-menu [my-cmd4]
              '(menu-item "Insert URL (auto-title)" ps/org-insert-link-async :help "Insert URL (auto-title)"))
  (define-key my-menu-bar-menu [my-cmd3]
              '(menu-item "Insert Obsidian Link (prompt)" ps/insert-obsidian-link-prompt :help "Insert [[obsidian:Title]] by typing title"))
  (define-key my-menu-bar-menu [my-cmd2]
              '(menu-item "Insert Obsidian Link (clipboard)" ps/insert-obsidian-link-from-clipboard :help "Insert [[obsidian:Title]] using clipboard"))
  (define-key my-menu-bar-menu [my-cmd1]
              '(menu-item "Collapse DONE tasks" ps/done-collapse))
  (define-key my-menu-bar-menu [my-cmd0]
              '(menu-item "Expand DONE tasks" ps/done-expand))
  (define-key my-menu-bar-menu [my-cmd-avail]
              '(menu-item "Show Availability" ps/org-show-availability :help "Show free time slots from org agenda"))
  (define-key my-menu-bar-menu [my-cmd-conflicts]
              '(menu-item "Check Conflicts" ps/show-conflicts :help "Show scheduling conflicts in org files"))
  (define-key my-menu-bar-menu [my-cmd-timezone]
              '(menu-item "Shift Timezones" ps/shift-timezone :help "Shift org timestamps to a new timezone"))
#+end_src

* Session Management and Backups
** Toggle horizontal and vertical split
#+begin_src emacs-lisp
  ;; Partially reuses the code from:
  ;; https://emacs.stackexchange.com/questions/5371/how-to-change-emacs-windows-from-vertical-split-to-horizontal-split
  (defun window-split-toggle ()
    "Toggle between horizontal and vertical split with exactly two windows, preserving buffer order."
    (interactive)
    ;; Check if NeoTree is open
    (let ((neo-open (neo-global--window-exists-p)))
      (when neo-open
        (neotree-hide))  ;; Hide NeoTree temporarily

      ;; Check if there are exactly two windows
      (if (/= (length (window-list)) 2)
          (error "Can only toggle with exactly 2 windows!")
        (let* ((win1 (nth 0 (window-list)))
               (win2 (nth 1 (window-list)))
               (buf1 (window-buffer win1))
               (buf2 (window-buffer win2))
               (split-func (if (window-full-height-p)
                               #'split-window-vertically
                             #'split-window-horizontally)))
          (delete-other-windows win1)
          (let ((new-win (funcall split-func)))
            (set-window-buffer win1 buf1)
            (set-window-buffer new-win buf2))))

      ;; Reopen NeoTree if it was open before
      (when neo-open
        (neotree-show))))

  (global-set-key (kbd "C-x |") 'window-split-toggle)
#+end_src

#+RESULTS:
: window-split-toggle

** Enable Magit for version control
#+begin_src emacs-lisp
  (use-package magit
    :bind (("C-x g" . magit-status))
    )
#+end_src

** Automatic Git Sync for Org Files
Logic lives in =lisp/ps-git-sync.el=. The interval is set in the Git Sync
Settings block above. =ps/git-sync-resume= clears the paused state after you
resolve a merge conflict.
#+begin_src emacs-lisp
  (ps/git-sync-start my-org-base-directory)
#+end_src

** Save and Restore Sessions
#+begin_src emacs-lisp
  ;; Save and restore the Emacs session (buffers, history, etc.)
  ;; https://emacs.stackexchange.com/questions/639/how-can-i-restart-emacs-and-preserve-my-open-buffers-and-interactive-history
  (desktop-save-mode 1)
  (savehist-mode 1)

  ;; Save the kill-ring to the history
  (add-to-list 'savehist-additional-variables 'kill-ring)

  ;; Reload desktop without asking
  ;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html
  (setq desktop-load-locked-desktop t)
#+end_src

** Backup and Autosave Configuration
#+begin_src emacs-lisp
  ;; Store backup files and auto-save files in a specific directory
  (setq backup-directory-alist `(("." . ,(expand-file-name "tmp/backups/" user-emacs-directory)))
        auto-save-list-file-prefix (expand-file-name "tmp/auto-saves/sessions/" user-emacs-directory)
        auto-save-file-name-transforms `((".*" ,(expand-file-name "tmp/auto-saves/" user-emacs-directory) t))
        ;; Disable lock files
        create-lockfiles nil)

  ;; Ensure the auto-save directory exists (auto-save-mode doesn't create it)
  (make-directory (expand-file-name "tmp/auto-saves/" user-emacs-directory) t)

  ;; Alternatives:
  ;; - https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-Tips-Cleaning.org
  ;; - no-littering package: https://github.com/emacscollective/no-littering
#+end_src
