;;; test-ps-info-triage.el --- ERT tests for ps-info-triage -*- lexical-binding: t; -*-

(require 'ert)
(require 'org)
(add-to-list 'load-path "lisp")
(require 'ps-info-triage)

(defconst ps/info-triage-test--queue
  "#+TITLE: Info triage inbox
#+SUBTITLE: 3 items, oldest 1 day — generated by sync.sh, do not edit
#+STARTUP: overview
# Reading this as an agent? Stop — read triage.md in this directory instead.

* 1 · 2026-08-14 · paper · Scalable Keyword Spotting via Modular Network Expansion
  /read before the Friday review/
  [[file:2026-08-14_146/index.md][index]] · [[file:2026-08-14_146/][directory]] · [[https://arxiv.org/abs/2607.19918][source]]

* 2 · 2026-08-16 · . (@marlidiuret) • Instagram photos and videos  :none:
  [[file:2026-08-16_156/index.md][index]] · [[file:2026-08-16_156/][directory]] · [[https://www.instagram.com/marlidiuret/][source]]

* 3 · 2026-08-16 · post · Ever noticed the colored tags on the ancient trees…  :partial:
  [[file:2026-08-16_165/index.md][index]] · [[file:2026-08-16_165/][directory]]
"
  "A queue in exactly the shape `render_org' (info_triage/sync.py) emits.
Includes the three cases that broke the old reader: an item with an intent
line between the heading and the links, an untitled item whose heading has no
kind at all, and one with no source link.")

(defmacro ps/info-triage-test--in-queue (&rest body)
  "Run BODY in an Org buffer holding the sample queue."
  (declare (indent 0))
  `(with-temp-buffer
     (insert ps/info-triage-test--queue)
     (let ((org-mode-hook nil))
       (org-mode))
     (goto-char (point-min))
     ,@body))

(defun ps/info-triage-test--goto (number)
  "Move point onto the heading of item NUMBER."
  (goto-char (point-min))
  (re-search-forward (format "^\\* %d " number))
  (beginning-of-line))

;;; -------------------------------------------------------
;;; Reading the item at point
;;; -------------------------------------------------------

(ert-deftest ps/info-triage--item-directory-reads-the-directory-link ()
  "The `directory' link is the only place the item's id still appears now that
the property drawer is gone, so this parse is a contract with the generator."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (should (equal (ps/info-triage--item-directory) "2026-08-14_146"))
    (ps/info-triage-test--goto 3)
    (should (equal (ps/info-triage--item-directory) "2026-08-16_165"))))

(ert-deftest ps/info-triage--item-directory-is-not-fooled-by-the-next-item ()
  "An item whose own links are missing must report nothing rather than the
directory of the item below it -- which is what a drop would then delete."
  (with-temp-buffer
    (insert "* 1 · 2026-08-14 · paper · No links here\n\n"
            "* 2 · 2026-08-15 · post · The next one\n"
            "  [[file:2026-08-15_152/index.md][index]] · [[file:2026-08-15_152/][directory]]\n")
    (let ((org-mode-hook nil)) (org-mode))
    (ps/info-triage-test--goto 1)
    (should-not (ps/info-triage--item-directory))))

(ert-deftest ps/info-triage--item-directory-works-from-inside-the-item ()
  "Point lands on the link line as often as on the heading."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (forward-line 1)
    (should (equal (ps/info-triage--item-directory) "2026-08-14_146"))))

(ert-deftest ps/info-triage--item-number-reads-the-heading ()
  "The number is what gets quoted to a routing agent, so it has to be exact."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 2)
    (should (equal (ps/info-triage--item-number) "2"))))

(ert-deftest ps/info-triage--item-number-copes-with-a-heading-that-has-no-kind ()
  "Item 2 in the sample is the degenerate case: nothing was extracted, so the
heading is number, date and label with the kind missing entirely."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 2)
    (should (equal (ps/info-triage--item-directory) "2026-08-16_156"))))

(ert-deftest ps/info-triage--item-path-refuses-above-the-first-item ()
  "Point in the file header is not point on an item, and a drop there would
otherwise be a delete of something unnamed."
  (ps/info-triage-test--in-queue
    (goto-char (point-min))
    (should-error (ps/info-triage--item-path) :type 'user-error)))

(ert-deftest ps/info-triage--item-label-drops-what-the-prompt-already-says ()
  "A confirmation that repeats the number and reads Org markup back at you is
one you stop reading, which is the opposite of what a delete prompt is for."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 3)
    (should (equal (ps/info-triage--item-label)
                   "post · Ever noticed the colored tags on the ancient trees…"))
    (ps/info-triage-test--goto 1)
    (should (equal (ps/info-triage--item-label)
                   "paper · Scalable Keyword Spotting via Modular Network Expansion"))))

;;; -------------------------------------------------------
;;; Availability -- what the menu is gated on
;;; -------------------------------------------------------

(ert-deftest ps/info-triage-available-p-follows-the-directory ()
  "The feature is hidden entirely on a machine without the inbox: this config
is shared, and a menu for a tool you do not have is noise."
  (let ((ps/info-triage-directory temporary-file-directory))
    (should (ps/info-triage-available-p)))
  (let ((ps/info-triage-directory "/nowhere/at/all/"))
    (should-not (ps/info-triage-available-p))))

(ert-deftest ps/info-triage-queue-buffer-p-matches-only-the-generated-queue ()
  (let* ((inbox (make-temp-file "ps-triage-test-" :directory))
         (ps/info-triage-directory (file-name-as-directory inbox))
         (queue (expand-file-name "triage.org" inbox))
         (other (expand-file-name "notes.org" inbox)))
    (unwind-protect
        (progn
          (write-region ps/info-triage-test--queue nil queue nil 'silent)
          (write-region "* a plan\n" nil other nil 'silent)
          (let ((queue-buffer (find-file-noselect queue))
                (other-buffer (find-file-noselect other)))
            (unwind-protect
                (progn
                  (should (ps/info-triage-queue-buffer-p queue-buffer))
                  (should-not (ps/info-triage-queue-buffer-p other-buffer)))
              (kill-buffer queue-buffer)
              (kill-buffer other-buffer))))
      (delete-directory inbox :recursive))))

(ert-deftest ps/info-triage-open-refuses-when-there-is-no-inbox ()
  (let ((ps/info-triage-directory "/nowhere/at/all/"))
    (should-error (ps/info-triage-open) :type 'user-error)))

;;; -------------------------------------------------------
;;; The queue buffer
;;; -------------------------------------------------------

(ert-deftest ps/info-triage-mode-makes-the-queue-read-only ()
  "It is regenerated wholesale on every sync, so anything typed here is lost
-- and saying so is what frees the single-key bindings."
  (ps/info-triage-test--in-queue
    (ps/info-triage-mode 1)
    (should buffer-read-only)
    (ps/info-triage-mode -1)
    (should-not buffer-read-only)))

(ert-deftest ps/info-triage-mode-remaps-org-link-following ()
  "Org puts its own keymap on a link as a text property, which outranks a
minor-mode map -- so only a remap reaches a click on a link.

Both commands must be remapped.  `org-mouse-map' binds mouse-2 to
`org-open-at-mouse', a separate command ending in a plain
`(org-open-at-point)' funcall -- and remapping rewrites dispatch, never a
funcall, so remapping only the second leaves every mouse click going through
stock Org handling and opening the item in another window."
  (ps/info-triage-test--in-queue
    (ps/info-triage-mode 1)
    (should (eq (command-remapping #'org-open-at-point) #'ps/info-triage-follow))
    (should (eq (command-remapping #'org-open-at-mouse)
                #'ps/info-triage-follow-at-mouse))))

;;; test-ps-info-triage.el ends here
